name: Predictions Workflow

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn joblib xgboost requests
          

      - name: Download and process database for predictions
        run: |
          python future_predictions.py  # Replace with your actual script name

      - name: Commit and push predictions to test repo
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Add future predictions database'
          add: 'future_predictions.db'

      - name: Push changes to test repo
        run: |
          git remote set-url origin https://github.com/chiragpalan/test.git
          git push origin main
