name: Update Stock Data

on:
  schedule:
    - cron: '30 16 * * *'  # Runs daily at 10 PM IST (16:30 UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install yfinance pandas

    - name: Run stock data update script
      run: python update_stock_data.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add update_project_plan/stock_data.db
        git commit -m "Update stock data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
