name: Train and Predict Models

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  train-and-predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Final Project Repository
        uses: actions/checkout@v3
        with:
          repository: chiragpalan/final_project  # Your source repo
          path: databse/joined_data.db  # Checkout data here

      - name: Checkout Test Repository
        uses: actions/checkout@v3  # Your destination repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn xgboost joblib

      - name: Run Training and Prediction Script
        run: python train_and_predict.py

      - name: Commit and Push Models and Predictions
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add models/ predictions.db
          git commit -m "Add trained models and predictions"
          git push
